version: '3'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    network_mode: bridge
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
